# Generated by Django 4.2.1 on 2023-05-14 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100, verbose_name='Localização')),
                ('cpfcnpj', models.CharField(max_length=100, verbose_name='CPF/CNPJ')),
                ('numero', models.IntegerField(verbose_name='Número')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=100)),
                ('nomePai', models.CharField(max_length=100)),
                ('numeroPai', models.CharField(max_length=100)),
                ('nomeMae', models.CharField(max_length=100)),
                ('numeroMae', models.CharField(max_length=100)),
                ('motivoBaixa', models.CharField(max_length=100)),
                ('partosNaoLancados', models.IntegerField()),
                ('dataNascimento', models.DateField()),
                ('dataBaixa', models.DateField()),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.fazenda')),
            ],
        ),
    ]
