# Generated by Django 4.2.1 on 2023-05-14 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualidadeLeite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nt', models.IntegerField(verbose_name='Número de Lactação')),
                ('dias', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('kgLeite', models.FloatField(verbose_name='Kg de Leite')),
                ('porcentagemGordura', models.FloatField(verbose_name='Porcentagem de Gordura')),
                ('porcentagemProteinas', models.FloatField(verbose_name='Porcentagem de Proteínas')),
                ('lactose', models.FloatField()),
                ('gp', models.FloatField(verbose_name='GP')),
                ('ccs', models.FloatField(verbose_name='CCS')),
                ('ureia', models.FloatField()),
                ('cetose', models.FloatField()),
                ('pps', models.FloatField(verbose_name='PPS')),
                ('diaRetirado', models.DateField(verbose_name='Dia Retirado')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.animal')),
            ],
        ),
    ]
