# Generated by Django 4.1.7 on 2023-05-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_qualidadeleite'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField()),
                ('medicamento', models.CharField(max_length=100)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.animal')),
            ],
        ),
    ]
