# Generated by Django 4.1.7 on 2023-05-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_historicoanimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasServ', models.IntegerField()),
                ('ultimaServ', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.animal')),
            ],
        ),
    ]
