# Generated by Django 4.1.7 on 2023-05-16 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_cio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanhoPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('pesoDia', models.FloatField(verbose_name='Peso por dia')),
                ('quantidadeRacao', models.FloatField(verbose_name='Quantidade de ração')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.animal')),
            ],
        ),
    ]
